### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Sunshine-hami/20200817__git#1]
1)
неправильное поведение элемента
![image](https://user-images.githubusercontent.com/8464662/91033872-bfcb7700-e60c-11ea-8413-a428e24d133e.png)
2)
![image](https://user-images.githubusercontent.com/8464662/91033928-d7a2fb00-e60c-11ea-93b4-815ff99e7f67.png)
3)
![image](https://user-images.githubusercontent.com/8464662/91033959-e1c4f980-e60c-11ea-839c-b7fb7e10f3d6.png)

4)
неправильный внешний вид
![image](https://user-images.githubusercontent.com/8464662/91033994-f0abac00-e60c-11ea-8375-5cda163c4f67.png)

5)
нет иконок
![image](https://user-images.githubusercontent.com/8464662/91034034-00c38b80-e60d-11ea-843d-2c0ad9d18453.png)

6)
требования минимальной высоты не выполнены
![image](https://user-images.githubusercontent.com/8464662/91034064-0c16b700-e60d-11ea-8475-2be2502e0732.png)

7)
неправильные отступы
![image](https://user-images.githubusercontent.com/8464662/91034121-218be100-e60d-11ea-8ec0-f6bc4dd5153c.png)

8)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/91034168-336d8400-e60d-11ea-869d-1570ab41bfa0.png)

**Comment by Alecto** [comment]
9)
размер шрифта не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/91437450-93189900-e872-11ea-8331-858243bb248e.png)

10)
нет соответсвия
![image](https://user-images.githubusercontent.com/8464662/91437489-a592d280-e872-11ea-8dd8-d3a3e552af4b.png)
![image](https://user-images.githubusercontent.com/8464662/91437505-adeb0d80-e872-11ea-9a9a-5a0cfd0b47f2.png)

**Comment by Alecto** [comment]
9 - не исправлено.
проверяйте все разрешения.

**Comment by Sunshine-hami** [comment]
https://github.com/Sunshine-hami/20200817__git

Здравствуйте, исправила

сб, 29 авг. 2020 г. в 20:57, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
ссылочку на страницу пожалуйста

пт, 4 вер. 2020 о 19:00 Sunshine-hami <notifications@github.com> пише:

**Comment by Sunshine-hami** [comment]
https://sunshine-hami.github.io/20200817__git/

сб, 5 сент. 2020 г. в 08:09, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
отлично.
кому оценку ставить?

сб, 5 вер. 2020 о 10:51 Sunshine-hami <notifications@github.com> пише:

**Comment by Sunshine-hami** [comment]
Пасечник Алёна

**Comment by Alecto** [comment]
отлично, отметил в журнале

сб, 5 вер. 2020 о 21:46 Sunshine-hami <notifications@github.com> пише:

**Comment by Sunshine-hami** [comment]
спасибо
